version: "3.9"  # optional since v1.27.0
services:
  bot:
    image: ghcr.io/SCBandChat-org/scbcb:master
    build: ./
    env_file:
      - stack.env
    volumes:
      - /home/nevana/scbcb/logs:/app/logs
      - /home/nevana/scbcb/foo.db:/app/foo.db